src/Entity/Feature.php
<?php

namespace App\Entity;

use App\Repository\FeatureRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FeatureRepository::class)
 */
class Feature
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Rating;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Matrix;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $Headphones;

    /**
     * @ORM\Column(type="integer")
     */
    private $WorkingHours;

    /**
     * @ORM\OneToOne(targetEntity=Products::class, inversedBy="feature", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $product;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRating(): ?int
    {
        return $this->Rating;
    }

    public function setRating(?int $Rating): self
    {
        $this->Rating = $Rating;

        return $this;
    }

    public function getMatrix(): ?string
    {
        return $this->Matrix;
    }

    public function setMatrix(string $Matrix): self
    {
        $this->Matrix = $Matrix;

        return $this;
    }

    public function getHeadphones(): ?bool
    {
        return $this->Headphones;
    }

    public function setHeadphones(?bool $Headphones): self
    {
        $this->Headphones = $Headphones;

        return $this;
    }

    public function getWorkingHours(): ?int
    {
        return $this->WorkingHours;
    }

    public function setWorkingHours(int $WorkingHours): self
    {
        $this->WorkingHours = $WorkingHours;

        return $this;
    }

    public function getProduct(): ?Products
    {
        return $this->product;
    }

    public function setProduct(Products $product): self
    {
        $this->product = $product;

        return $this;
    }
}

src/Controller/CatalogController.php
<?php

namespace App\Controller;


use App\Entity\Comment;
use App\Entity\Products;
use App\Entity\User;
use App\Form\AddCommentFormType;
use App\Service\CategoryService;
use App\Service\ProductsService;
use App\Service\ViewHistoryService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class CatalogController extends AbstractController
{
    private CategoryService $categoryService;
    private ProductsService $productsService;
    private ViewHistoryService $viewHistoryService;

    public function __construct(
        CategoryService $categoryService,
        ProductsService $productsService,
        ViewHistoryService $viewHistoryService
    ) {
        $this->categoryService = $categoryService;
        $this->productsService = $productsService;
        $this->viewHistoryService = $viewHistoryService;
    }

    /**
     * @Route("/catalog", name="app_catalog")
     */
    public function catalog(PaginatorInterface $paginator, Request $request): Response
    {
        $perPage = $request->query->getInt('perPage', 20);

        $pagination = $paginator->paginate(
            $this->productsService->getAllWithSearchQuery(
                $request->query->get('q')),
            $request->query->getInt('page', 1),
            $perPage
        );

        $categories = $this->categoryService->getCategory();

        return $this->render('catalog/catalog.html.twig', [
            'categories' => $categories,
            'pagination' => $pagination,
        ]);
    }

    /**
     * @Route("/catalog/ptoducts/{slug}", name="app_catalog_show")
     */
    public function show(Products $products, $slug, Request $request, EntityManagerInterface $em): Response
    {
        $categories = $this->categoryService->getCategory();
        $sellerNames = $this->productsService->getSellerByProductId($slug);

        $user = $this->getUser();
        if ($user instanceof User) {
            $this->viewHistoryService->addToViewHistory($user, $products);
        }

        $form = $this->createForm(AddCommentFormType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Comment $comment */
            $comment = $form->getData();

            $comment
                ->setUser($user)
                ->setProduct($products)
                ->setCreatedAt(new \DateTime())
                ->setUpdatedAt(new \DateTime())
            ;

            $em->persist($comment);
            $em->flush();

            $this->addFlash('flash_message', 'Товар успешно создан');

            return $this->redirectToRoute('app_account');
        }

        return $this->render('catalog/product.html.twig', [
            'categories' => $categories,
            'products' => $products,
            'sellerNames' => $sellerNames,
            'AddCommentForm' => $form->createView(),
        ]);
    }

    /**
     * @Route("/catalog/compare", name="app_catalog_compare")
     */
    public function compare(): Response
    {
        $categories = $this->categoryService->getCategory();
        return $this->render('catalog/compare.html.twig', [
            'categories' => $categories,
        ]);
    }
}

templates/catalog/catalog.html.twig
{% extends 'base.html.twig' %}

{% block slider %}{% endblock %}

{% block body %}
<div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">Каталог</h1>
                <ul class="breadcrumbs Middle-breadcrumbs">
                    <li class="breadcrumbs-item"><a href="{{ path('app_homepage') }}">Главная</a></li>
                    <li class="breadcrumbs-item breadcrumbs-item_current"><span>Каталог</span></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
        <div class="wrap">
            <div class="Section-column">
                <div class="Section-columnSection">
                    <header class="Section-header">
                        <strong class="Section-title">Фильтр</strong>
                    </header>
                    <div class="Section-columnContent">
                        <form class="form" >
                            <div class="form-group">
                                <div class="range Section-columnRange">
                                    <input class="range-line" id="price" name="price" type="text" data-type="double" data-min="7" data-max="50" data-from="7" data-to="27"/>
                                    <div class="range-price">Цена:&#32;
                                        <div class="rangePrice"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <input class="form-input form-input_full" id="title" name="q" type="text" placeholder="Название" value="{{ app.request.query.get('q') }}"/>
                            </div>
                            <div class="form-group">
                                <select class="form-select">
                                    <option selected="selected" disabled="disabled">Продавец</option>
                                    <option value="kkk">Kkkk</option>
                                    <option value="sdfsdf">sdfsdf</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="toggle">
                                    <input type="checkbox"/><span class="toggle-box"></span><span class="toggle-text">Только с небитым экраном</span>
                                </label>
                            </div>
                            <div class="form-group">
                                <select class="form-select" multiple size="4">
                                    <option disabled="disabled">Объем памяти</option>
                                    <option>1Гб</option>
                                    <option>2Гб</option>
                                    <option>4Гб</option>
                                    <option>8Гб</option>
                                    <option>многоГб</option>
                                    <option>оченьмногоГб</option>
                                    <option>взвесьтемнеполкилоГб</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <div><button class="buttons btn btn_square btn_dark btn_narrow" type="submit">Применить</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="Section-content">
                <div class="Sort">
                    <div class="Sort-title">Сортировать по:
                    </div>
                    <div class="Sort-variants">
                        <a
                                class="Sort-sortBy"
                                data-item="sort"
                                data-type="desc"
                                data-desc-href="{{ path('app_catalog', { type: 'desc'}) }}"
                                data-asc-href="{{ path('app_catalog', { type: 'asc'}) }}"
                        >Популярности</a>
                        <a class="Sort-sortBy" href="#">Цене</a>
                        <a class="Sort-sortBy" href="#">Отзывам</a>
                        <a class="Sort-sortBy Sort-sortBy_inc" href="#">Новизне</a>
                    </div>

                </div>
                <div class="Cards" id="productsContainer">
                    {% for product in pagination %}
                        <div class="Card"><a class="Card-picture" href="{{ path('app_catalog_show', { slug: product.slug }) }}"><img src="{{ product.imageFilename }}" alt="card.jpg"/></a>
                            <div class="Card-content">
                                <strong class="Card-title"><a href="{{ path('app_catalog_show', { slug: product.slug }) }}">{{ product.product }}</a>
                                </strong>
                                <div class="Card-description">
                                    {% if product.discounts is not null %}
                                        {% set discountedPrice = product.prices.first.price - product.prices.first.price * product.discounts.value / 100 %}
                                        <div class="Card-cost">
                                            <span class="Card-priceOld">${{ product.prices.first.price }}</span><span class="Card-price">${{ discountedPrice }}</span>
                                        </div>
                                    {% else %}
                                        <div class="Card-cost">
                                            <span class="Card-price">${{ product.prices.first.price }}</span>
                                        </div>
                                    {% endif %}
                                    <div class="Card-category">{{ product.category.name }}
                                    </div>
                                    <div class="Card-hover"><a class="Card-btn" href="{{ path('app_catalog_show', { slug: product.slug }) }}"><img src="{{ asset('assets/img/icons/card/bookmark.svg') }}" alt="bookmark.svg"/></a><a class="Card-btn" href="{{ path('app_cart_addtocart', { id: product.id } ) }}"><img src="{{ asset('assets/img/icons/card/cart.svg') }}" alt="cart.svg"/></a><a class="Card-btn" href="{{ path('app_add_to_comparison', {id: product.id}) }}"><img src="{{ asset('assets/img/icons/card/change.svg') }}" alt="change.svg"/></a>
                                    </div>
                                </div>
                            </div>
                            {% if product.discounts is not null %}
                                <div class="Card-sale">
                                    -{{ product.discounts.value }}%
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
                <div class="Pagination">
                    <div class="Pagination-ins">
                        {{ knp_pagination_render(pagination) }}
                    </div>
                </div
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/catalog/product.html.twig
{% extends 'base.html.twig' %}

{% block slider %}{% endblock %}

{% block stylesheet %}
    {{ encore_entry_link_tags('app') }}
{% endblock %}

{% block body %}
<div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">Товар</h1>
                <ul class="breadcrumbs Middle-breadcrumbs">
                    <li class="breadcrumbs-item"><a href="{{ path('app_homepage') }}">Главная</a></li>
                    <li class="breadcrumbs-item"><a href="{{ path('app_catalog') }}">Каталог</a></li>
                    <li class="breadcrumbs-item"><a href="{{ path('app_catalog') }}">{{ products.category.name }}</a></li>
                    <li class="breadcrumbs-item breadcrumbs-item_current"><span>Товар</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="Section">
        <div class="wrap">
            <div class="Product">
                <div class="ProductCard">
                    <div class="ProductCard-look">
                        <div class="ProductCard-photo">
                            {% if products.discounts is not null %}<div class="ProductCard-sale">{{ products.discounts.value }}%
                            </div>{% endif %}<img src="{{ asset(products.imageFilename) }}" alt="bigGoods.png"/>
                        </div>
                        <div class="ProductCard-picts"><a class="ProductCard-pict ProductCard-pict_ACTIVE" href="{{ asset(products.imageFilename) }}"><img src="{{ asset(products.imageFilename) }}" alt="bigGoods.png"/></a><a class="ProductCard-pict" href="{{ asset('assets/img/content/home/slider.png') }}"><img src="{{ asset('assets/img/content/home/slider.png') }}" alt="slider.png"/></a><a class="ProductCard-pict" href="{{ asset('assets/img/content/home/videoca.png') }}"><img src="{{ asset('assets/img/content/home/videoca.png') }}" alt="videoca.png"/></a>
                        </div>
                    </div>
                    <div class="ProductCard-desc">
                        <div class="ProductCard-header">
                            <h2 class="ProductCard-title">{{ products.description }}</h2>
                            <div class="ProductCard-info">
                                <div class="ProductCard-cost">
                                    {% if products.discounts is not null %}
                                    <div class="ProductCard-price">
                                            {% set discountedPrice = products.prices.first.price - products.prices.first.price * products.discounts.value / 100 %}
                                            ${{ discountedPrice }}
                                    </div>
                                    <div class="ProductCard-priceOld">
                                        ${{ products.prices.first.price }}
                                    </div>
                                    {% else %}
                                    <div class="ProductCard-price">
                                        ${{ products.prices.first.price }}
                                    </div>
                                    {% endif %}
                                </div>
                                <div class="ProductCard-compare">
                                    <a class="btn btn_default" href="{{ path('app_add_to_comparison', { id: products.id }) }}"><img class="btn-icon" src="{{ asset('assets/img/icons/card/change.svg') }}" alt="change.svg"/></a>
                                </div>
                            </div>
                        </div>
                        <div class="ProductCard-text">
                            <ul>
                                {{ products.body }}
                            </ul>
                        </div>
                        <div class="ProductCard-cart">
                            <div class="ProductCard-cartElement ProductCard-cartElement_amount">
                                <div class="Amount Amount_product">
                                    <button class="Amount-remove" type="button"></button>
                                    <input class="Amount-input form-input" name="amount" type="text" value="1"/>
                                    <button class="Amount-add" type="button"></button>
                                </div>
                            </div>
                            <div class="ProductCard-cartElement"><a class="btn btn_primary" href="{{ path('app_cart_addtocart', { id: products.id }) }}"><img class="btn-icon" src="{{ asset('assets/img/icons/card/cart_white.svg') }}" alt="cart_white.svg"/><span class="btn-content">Купить</span></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="Tabs Tabs_default">
                    <div class="Tabs-links">
                        <a class="Tabs-link_ACTIVE Tabs-link" href="#description"><span>Описание</span></a>
                        <a class="Tabs-link" href="#sellers"><span>Продавцы</span></a>
                        <a class="Tabs-link" href="#addit"><span>Характеристики</span></a>
                        <a class="Tabs-link" href="#reviews"><span>Отзывы ({{ products.comments|length }})</span></a>
                    </div>
                    <div class="Tabs-wrap">
                        <div class="Tabs-block" id="description">
                            <h2>{{ products.product }}</h2>
                            <p>{{ products.description }}
                            </p><img class="pict pict_right" src="{{ asset('assets/img/content/home/bigGoods.png') }}" alt="bigGoods.png"/>
                            <ul>
                                {{ products.body }}
                            </ul>
                            <div class="clearfix">
                            </div>
                            <div class="table">
                                <table>
                                    <tr>
                                        <th>Табличка внутри описания</th>
                                        <th>Значение
                                        </th>
                                    </tr>
                                    <tr>
                                        <td>ываыв</td>
                                        <td>llslssl
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                        <div class="Tabs-block" id="sellers">
                            <div class="Categories Categories_product">
                                {% for sellerName in sellerNames %}
                                    <div class="Categories-row">
                                        <div class="Categories-block Categories-block_info">
                                            <div class="Categories-info">
                                                <strong><a href="{{ path('app_seller', { slug: sellerName.sellerSlug }) }}">{{ sellerName.sellerName }}</a>
                                                </strong>
                                            </div>
                                        </div>
                                        <div class="Categories-splitProps">
                                        </div>
                                        <div class="Categories-block Categories-price">
                                            <strong>$&#32;{{ sellerName.priceValue }}
                                            </strong>
                                        </div>
                                        <div class="Categories-block Categories-button"><a class="btn btn_primary" href="#"><img class="btn-icon" src="{{ asset('assets/img/icons/card/cart_white.svg') }}" alt="cart_white.svg"/><span class="btn-content">Купить</span></a>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="Tabs-block" id="addit">
                            <div class="Product-props">
                                <div class="Product-prop">
                                    <strong>Рейтинг
                                    </strong><span> {{ products.feature.rating }}</span>
                                </div>
                                <div class="Product-prop">
                                    <strong>Матрица
                                    </strong><span>{{ products.feature.matrix }}</span>
                                </div>
                                <div class="Product-prop">
                                    <strong>Наушники в комплекте
                                    </strong><span>{{ products.feature.headphones ? 'Yes' : 'No' }}</span>
                                </div>
                                <div class="Product-prop">
                                    <strong>Время работы
                                    </strong><span>{{ products.feature.workingHours }} часов</span>
                                </div>
                            </div>
                        </div>
                        <div class="Tabs-block" id="reviews">
                            <div class="Comments">
                                <div class="Comment">
                                    <div class="Comment-column Comment-column_pict">
                                        <div class="Comment-avatar">
                                        </div>
                                    </div>
                                    <div class="Comment-column">
                                        <header class="Comment-header">
                                            <div>
                                                <strong class="Comment-title">{{ products.comments.first.user.firstName}}
                                                </strong><span class="Comment-date">{{ products.comments.first.createdAt|date('d-m-Y-H-i-s') }}</span>
                                            </div>
                                        </header>
                                        <div class="Comment-content">
                                            {{ products.comments.first.content }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <header class="Section-header Section-header_product">
                                <h3 class="Section-title">Оставить отзыв</h3>
                            </header>
                            <div class="Tabs-addComment">
                                <form class="form" action="#" method="post">
                                    {{ form_start(AddCommentForm) }}
                                    <div class="form-group">
                                        {{ form_row(AddCommentForm.content) }}
                                    </div>
                                    <div class="form-group">
                                        <div class="row">
                                            <div class="row-block">
                                                {{ app.user.firstName }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn_muted" type="submit">Оставить отзыв</button>
                                    </div>
                                    {{ form_end(AddCommentForm) }}
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block javascripts %}
    {{ encore_entry_script_tags('app') }}
{% endblock %}